# Definizione di un workflow di build su Codemagic
workflows:
  # Il nome del workflow.
  ios-build-workflow:
    name: iOS Build and Publish

    # Durata massima del build in minuti, per evitare build infiniti.
    max_build_duration: 60

    # Definizione dell'ambiente di compilazione.
    environment:
      # Scegliere la versione di Xcode più recente per le app iOS.
      xcode: latest
      # Scegliere la versione di Node.js.
      node: '18'
      # Variabili d'ambiente, utili per riutilizzare lo stesso nome dell'app.
      vars:
        APP_NAME: "GestionaleEmerals"
        # Il Bundle ID della tua app, lo stesso che hai usato per Capacitor.
        APP_IDENTIFIER: "com.emeralstrasporti.gestionale"

    # La sezione degli script, dove vengono eseguiti tutti i comandi.
    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Fix permissions
        script: |
          # Questo comando risolve l'errore di permessi.
          # Imposta il permesso di esecuzione (+x) per il binario 'cap'.
          chmod +x ./node_modules/.bin/cap

      - name: Add and Sync iOS Platform
        script: |
          npx cap add ios
          npx cap sync ios

      - name: Build iOS App
        script: |
          cd ios
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $PWD/build/$APP_NAME.xcarchive

    # Definizione degli artefatti, ovvero i file da salvare dopo un build.
    artifacts:
      - ios/build/**/*.ipa

    # Sezione di publishing, per caricare automaticamente l'app su App Store Connect.
    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID