# Definizione di un workflow di build su Codemagic
workflows:
  ios-build-workflow:
    name: iOS Build and Publish

    # Durata massima del build in minuti.
    max_build_duration: 60

    # Definizione dell'ambiente di compilazione.
    environment:
      xcode: latest
      node: '18'
      vars:
        APP_NAME: "GestionaleEmerals"
        APP_IDENTIFIER: "com.emeralstrasporti.gestionale"

    # La sezione degli script.
    scripts:
      - name: Install dependencies and configure Capacitor
        script: |
          # Installa tutte le dipendenze.
          npm install
          
          # Imposta i permessi di esecuzione per il binario di Capacitor.
          chmod +x ./node_modules/.bin/cap

          # Aggiunge la piattaforma iOS e sincronizza i file web.
          # Eseguire i comandi in un unico blocco li rende più robusti.
          npx cap add ios
          npx cap sync ios

          # Verifica se il workspace è stato creato, altrimenti il build fallirà.
          if [ ! -d "ios/App.xcworkspace" ]; then
            echo "Error: App.xcworkspace was not created by Capacitor."
            exit 1
          fi

      - name: Build iOS App
        script: |
          cd ios
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $PWD/build/$APP_NAME.xcarchive

    # Definizione degli artefatti.
    artifacts:
      - ios/build/**/*.ipa

    # Sezione di publishing, per caricare automaticamente l'app su App Store Connect.
    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID