# Definizione di un workflow di build su Codemagic
workflows:
  ios-build-workflow:
    name: iOS Build and Publish

    # Durata massima del build in minuti.
    max_build_duration: 60

    # Definizione dell'ambiente di compilazione.
    environment:
      xcode: latest
      node: '20'
      vars:
        APP_NAME: "GestionaleEmerals"
        APP_IDENTIFIER: "com.emeralstrasporti.gestionale"

    # La sezione degli script.
    scripts:
      - name: Clean up and install dependencies
        script: |
          echo "Removing existing node_modules and ios directory for a clean build..."
          rm -rf node_modules ios
          npm install

      - name: Configure Capacitor and check for iOS platform
        script: |
          chmod +x ./node_modules/.bin/cap
          
          echo "Adding iOS platform..."
          npx cap add ios
          
          # Check if the ios directory was created successfully
          if [ ! -d "ios" ]; then
            echo "Error: The 'ios' directory was not created by 'npx cap add ios'. Check previous logs for errors."
            exit 1
          fi

          echo "Synchronizing web assets..."
          npx cap sync ios

      - name: Build iOS App
        script: |
          cd ios
          if [ ! -d "App.xcworkspace" ]; then
            echo "Error: App.xcworkspace does not exist in the ios directory."
            exit 1
          fi

          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $PWD/build/$APP_NAME.xcarchive

    # Definizione degli artefatti.
    artifacts:
      - ios/build/**/*.ipa

    # Sezione di publishing.
    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID