# Definizione di un workflow di build su Codemagic
workflows:
  ios-build-workflow:
    name: iOS Build and Publish
    max_build_duration: 60
    environment:
      xcode: latest
      node: '20'
      vars:
        APP_NAME: "GestionaleEmerals"
        APP_IDENTIFIER: "com.emeralstrasporti.gestionale"
    
    scripts:
      - name: Clean up and install dependencies
        script: |
          echo "Removing existing node_modules, ios and www directory..."
          rm -rf node_modules ios www
          npm install

      - name: Prepare web assets and configure Capacitor
        script: |
          echo "Preparing web assets directory..."
          mkdir www
          
          mv index.html www/ || true
          mv style.css www/ || true
          mv main.js www/ || true
          mv firebaseConfig.js www/ || true
          mv logo.jpg www/ || true
          mv Cursore1.png www/ || true
          
          chmod +x ./node_modules/.bin/cap

          echo "Initializing Capacitor..."
          npx cap init "$APP_NAME" "$APP_IDENTIFIER" --web-dir www

          echo "Adding iOS platform..."
          npx cap add ios

          echo "Synchronizing native dependencies..."
          npx cap sync ios

          # Questo è il passaggio chiave per risolvere l'errore
          echo "Installing CocoaPods dependencies..."
          cd ios
          pod install

      - name: Build iOS App
        script: |
          # Per sicurezza, torniamo alla cartella principale
          cd ..
          
          # Ora verifichiamo l'esistenza del workspace prima di buildare
          if [ ! -d "ios/App.xcworkspace" ]; then
            echo "Error: App.xcworkspace does not exist in the ios directory."
            exit 1
          fi

          echo "Building iOS archive..."
          xcodebuild -workspace ios/App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $PWD/build/$APP_NAME.xcarchive

    artifacts:
      - ios/build/**/*.ipa
    
    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
