# Definizione di un workflow di build su Codemagic
workflows:
  ios-build-workflow:
    name: iOS Build and Publish
    max_build_duration: 60
    environment:
      xcode: latest
      node: '20'
      vars:
        APP_NAME: "GestionaleEmerals"
        APP_IDENTIFIER: "com.emeralstrasporti.gestionale"
    
    scripts:
      - name: Clean up and install dependencies
        script: |
          echo "Removing existing node_modules, ios and www directory..."
          rm -rf node_modules ios www
          npm install

      - name: Prepare web assets and configure Capacitor
        script: |
          echo "Preparing web assets directory..."
          mkdir www
          
          # Sposta i file uno a uno in modo esplicito, ignorando gli errori se un file non esiste.
          mv index.html www/ || true
          mv style.css www/ || true
          mv main.js www/ || true
          mv firebaseConfig.js www/ || true
          mv logo.jpg www/ || true
          mv Cursore1.png www/ || true
          
          # Imposta i permessi di esecuzione per il binario di Capacitor
          chmod +x ./node_modules/.bin/cap

          # Inizializza Capacitor, creando il file capacitor.config.json in modo affidabile
          echo "Initializing Capacitor..."
          npx cap init "$APP_NAME" "$APP_IDENTIFIER" --web-dir www

          # Aggiunge la piattaforma iOS
          echo "Adding iOS platform..."
          npx cap add ios

          # Sincronizza i file web con il progetto iOS
          echo "Synchronizing web assets..."
          npx cap sync ios

      - name: Build iOS App
        script: |
          # Vai alla directory ios e verifica l'esistenza del workspace
          cd ios
          if [ ! -d "App.xcworkspace" ]; then
            echo "Error: App.xcworkspace does not exist in the ios directory. Build script failed to create it."
            exit 1
          fi

          echo "Building iOS archive..."
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $PWD/build/$APP_NAME.xcarchive

    artifacts:
      - ios/build/**/*.ipa
    
    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
