# Definizione di un workflow di build su Codemagic
workflows:
  ios-build-workflow:
    name: iOS Build and Publish
    max_build_duration: 60
    environment:
      xcode: latest
      node: '20'
      vars:
        APP_NAME: "GestionaleEmerals"
        APP_IDENTIFIER: "com.emeralstrasporti.gestionale"
    
    scripts:
      - name: Clean up and install dependencies
        script: |
          echo "Removing existing node_modules, ios and www directory..."
          rm -rf node_modules ios www
          npm install

      - name: Prepare web assets and configure Capacitor
        script: |
          echo "Preparing web assets directory..."
          mkdir www
          
          # Sposta i file uno a uno solo se esistono per evitare errori
          if [ -f "index.html" ]; then mv index.html www/ || true; fi
          if [ -f "style.css" ]; then mv style.css www/ || true; fi
          if [ -f "main.js" ]; then mv main.js www/ || true; fi
          if [ -f "firebaseConfig.js" ]; then mv firebaseConfig.js www/ || true; fi
          if [ -f "logo.jpg" ]; then mv logo.jpg www/ || true; fi
          if [ -f "Cursore1.png" ]; then mv Cursore1.png www/ || true; fi
          
          chmod +x ./node_modules/.bin/cap

          echo "Initializing Capacitor..."
          npx cap init "$APP_NAME" "$APP_IDENTIFIER" --web-dir www

          echo "Adding iOS platform..."
          npx cap add ios

          echo "Synchronizing native dependencies..."
          npx cap sync ios

          # Questo è il passaggio chiave, ora con il percorso corretto
          echo "Installing CocoaPods dependencies..."
          cd ios/App
          pod install

      - name: Build iOS App
        script: |
          # Per sicurezza, torniamo alla cartella principale
          cd ../..
          
          # Ora verifichiamo l'esistenza del workspace prima di buildare
          if [ ! -d "ios/App.xcworkspace" ]; then
            echo "Error: App.xcworkspace does not exist in the ios directory."
            exit 1
          fi

          echo "Building iOS archive..."
          xcodebuild -workspace ios/App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $PWD/build/$APP_NAME.xcarchive

    artifacts:
      - ios/build/**/*.ipa
    
    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
