# Definizione di un workflow di build su Codemagic
workflows:
  ios-build-workflow:
    name: iOS Build and Publish
    max_build_duration: 60
    environment:
      xcode: latest
      node: '20'
      vars:
        APP_NAME: "GestionaleEmerals"
        APP_IDENTIFIER: "com.emeralstrasporti.gestionale"
    
    scripts:
      - name: Clean up, install dependencies and prepare web assets
        script: |
          # Rimuove le cartelle node_modules e ios per un build pulito
          echo "Removing existing node_modules, ios and www directory..."
          rm -rf node_modules ios www

          # Installa le dipendenze
          npm install

          # Crea la cartella 'www' e sposta i file web al suo interno
          echo "Preparing web assets directory..."
          mkdir www
          
          # Spostiamo i file uno a uno in modo esplicito per evitare errori
          mv index.html www/
          mv style.css www/
          mv main.js www/
          mv firebaseConfig.js www/
          mv logo.jpg www/
          mv Cursore1.png www/
          
          # Verifica che i file siano stati spostati correttamente
          echo "Verifying files in www directory:"
          ls -la www/
          
          # Inizializza Capacitor e configura la directory web
          npx cap init --web-dir www "$APP_NAME" "$APP_IDENTIFIER"

      - name: Configure and Sync iOS Platform
        script: |
          # Imposta i permessi di esecuzione per il binario di Capacitor
          chmod +x ./node_modules/.bin/cap

          # Aggiunge la piattaforma iOS
          echo "Adding iOS platform..."
          npx cap add ios

          # Sincronizza i file web con il progetto iOS
          echo "Synchronizing web assets..."
          npx cap sync ios

      - name: Build iOS App
        script: |
          # Vai alla directory ios e verifica l'esistenza del workspace
          cd ios
          if [ ! -d "App.xcworkspace" ]; then
            echo "Error: App.xcworkspace does not exist in the ios directory. Build script failed to create it."
            exit 1
          fi

          echo "Building iOS archive..."
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $PWD/build/$APP_NAME.xcarchive

    artifacts:
      - ios/build/**/*.ipa
    
    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID 